version: "3"
services:
  node:
    build: .
    container_name: user-microservice
    restart: always
    volumes:
      - ./src:/app/src
      - ../../protobuf:/app/src/_proto
    environment:
      TZ: Asia/Bangkok
      LOGGING: "true"
      LOGGING_DISPLAY_SQL: "true"
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: user
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - 50051:50051
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default
      - microservice-link
    depends_on:
      - "postgres"
  postgres:
    image: postgres:16-alpine
    container_name: user-postgres
    ports:
      - 5433:5432
    # volumes:
    #   - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user
networks:
  microservice-link:
    external:
      name: microservice-link
